FROM golang:1.12.7-alpine as builder
WORKDIR $GOPATH/src/github.com/morganzero/traxync/
RUN apk add --no-cache git
COPY . .
RUN mkdir /out
RUN mkdir /out/keystore

RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/traxync-docker
FROM scratch
LABEL maintainer="morganzero@sushibox.dev"
WORKDIR /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /out .
COPY static ./static
VOLUME /app/keystore/
EXPOSE 8000
ENTRYPOINT ["/app/traxync-docker"]